version: '0.2'
sources:
- name: sandbox
  target: sandbox
  index: README.md
  type: local
  writeable: true
  quests: null
- name: ed
  target: https://github.com/qxcodeed/arcade.git
  index: README.md
  type: git
  writeable: false
  quests: null
- name: eval1
  target: https://github.com/senapk/eval_26_ed_1
  index: README.md
  type: git
  writeable: false
  quests: null
expanded:
- ed@map_set
- ed@list
- ed@rec
- sandbox@sandbox
- ed@backtrack
- ed@basic
- eval1@eval1
- ed@linear
- ed@bfs
- ed@tree
- ed@dfs
- ed@vector
flags:
  inbox: all
  panel: skills
  show_panel: 'true'
  task_graph_mode: executions
  show_time: 'true'
lang: go
selected: ed@tree
selected_index: 79
